version: "3.7"
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_wordpress:latest
    container_name: ${COMPOSE_PROJECT_NAME}-app
    tty: true
    privileged: true
    stdin_open: true
    depends_on:
      - "database"
    networks:
      - backend
      - database
    environment:
      DB_PORT: "3306"
      DB_HOST: "database"
      WEB_PORT: ${WEB_PORT}
      WEB_HTTP_PORT: ${WEB_HTTPS_PORT}
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    volumes:
      - ./www:/var/www/html
      - composerdata:/root/.composer/

  # Banco de Dados
  database:
    image: mysql:${MYSQL_IMAGE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    command: --mysql-native-password=ON
    environment:
      MYSQL_DATABASE: wp_${COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - database
    ports:
      - "${DB_PORT}:3306"

    # 1 - salvando os dados do banco no volume apontado para a máquina host do container, para evitar perdas inesperadas
    # 2 - executando os scripts desta pasta quando o container for executado
    volumes:
      - db_liceu_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
  # Security Scan
  wp_scan:
    build:
      context: ./docker
      dockerfile: wp_scan.Dockerfile
      args:
        IMAGE_VERSION: ${WP_SCAN_IMAGE_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_wpscan:latest
    command: "--url=http://web --disable-tls-checks --random-user-agent  --ignore-main-redirect -e ap,at,tt,cb,dbe,u,m"
    environment:
      - WPSCAN_API_TOKEN=${WPSCAN_API_TOKEN}
    networks:
      - backend
    profiles:
      - test
      - scan
    container_name: ${COMPOSE_PROJECT_NAME}-wp_scan
    volumes:
      - ./.wpscan:/wpscan

networks:
  backend:
  database:

volumes:
  db_liceu_data:
    driver: local
    labels:
      okn.project.name: ${COMPOSE_PROJECT_NAME}
  composerdata:
    driver: local
    labels:
      okn.project.name: ${COMPOSE_PROJECT_NAME}
